# Generated by Django 4.2.2 on 2023-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('CMPLT', 'Complete'), ('PR', 'In_process'), ('W', 'Waiting')], default='W', max_length=10)),
                ('priority', models.CharField(choices=[('HIGH', 'high'), ('MIDDLE', 'middle'), ('LOW', 'low')], default='HIGH', max_length=10)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
    ]
