# Generated by Django 4.2.2 on 2023-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Высокий', 'high'), ('Средний', 'middle'), ('Низкий', 'low')], default='Высокий', max_length=10),
        ),
    ]
