# Generated by Django 4.2.2 on 2023-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Высокий', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('В процессе', 'В процессе'), ('Ожидает выполнения', 'Ожидает выполнения')], default='Ожидает выполнения', max_length=20),
        ),
    ]
